services:
  postgres:
    image: postgres:16.3
    container_name: database
    restart: unless-stopped
    attach: false
    environment:
      POSTGRES_DB: "box"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "3bxMue16ztXPR635"
      TZ: 'GMT-4'
      PGTZ: 'GMT-4'
    volumes:
      - ./system/database:/var/lib/postgresql/data
      - ./src/migrations/001-init.sql:/docker-entrypoint-initdb.d/001-init.sql
      - ./src/migrations/002-i18n.sql:/docker-entrypoint-initdb.d/002-i18n.sql
    ports:
      - "8081:5432"

  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.app
    image: box/app:latest
    container_name: app
    restart: unless-stopped
    attach: false
    depends_on:
      - postgres
    volumes:
      - ./etc:/home/app/etc
      - ./system:/home/app/system
      - ./var/data:/home/app/var/data
      - ./var/lib:/home/app/var/lib
      - ./var/logs:/home/app/var/logs
      - ./var/test:/home/app/var/test

  authentication-service:
#    build:
#      context: .
#      dockerfile: Dockerfile.authentication-service
    image: box/authentication-service:latest
    container_name: authentication-service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./etc:/home/app/etc
      - ./system:/home/app/system
      - ./var/data:/home/app/var/data
      - ./var/lib:/home/app/var/lib
      - ./var/logs:/home/app/var/logs
      - ./var/test:/home/app/var/test

  i18n-service:
    build:
      context: .
      dockerfile: Dockerfile.i18n-service
    image: box/i18n-service:latest
    container_name: i18n-service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./etc:/home/app/etc
      - ./system:/home/app/system
      - ./var/data:/home/app/var/data
      - ./var/lib:/home/app/var/lib
      - ./var/logs:/home/app/var/logs
      - ./var/test:/home/app/var/test

  project_manager-service:
#    build:
#      context: .
#      dockerfile: Dockerfile.project_manager-service
    image: box/project_manager-service:latest
    container_name: project_manager-service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./etc:/home/app/etc
      - ./system:/home/app/system
      - ./var/data:/home/app/var/data
      - ./var/lib:/home/app/var/lib
      - ./var/logs:/home/app/var/logs
      - ./var/test:/home/app/var/test

  setup-service:
#    build:
#      context: .
#      dockerfile: Dockerfile.setup-service
    image: box/setup-service:latest
    container_name: setup-service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./etc:/home/app/etc
      - ./system:/home/app/system
      - ./var/data:/home/app/var/data
      - ./var/lib:/home/app/var/lib
      - ./var/logs:/home/app/var/logs
      - ./var/test:/home/app/var/test

  user_manager-service:
#    build:
#      context: .
#      dockerfile: Dockerfile.user_manager-service
    image: box/user_manager-service:latest
    container_name: user_manager-service
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./etc:/home/app/etc
      - ./system:/home/app/system
      - ./var/data:/home/app/var/data
      - ./var/lib:/home/app/var/lib
      - ./var/logs:/home/app/var/logs
      - ./var/test:/home/app/var/test

  nginx:
    image: nginx:1.27.0
    container_name: proxy
    restart: unless-stopped
    attach: false
    depends_on:
      - app
      - authentication-service
      - i18n-service
      - project_manager-service
      - setup-service
      - user_manager-service
    volumes:
      - type: bind
        source: ./system/nginx/proxy
        target: /etc/nginx/proxy
        consistency: cached
      - type: bind
        source: ./system/nginx/box.samgk.ru.conf
        target: /etc/nginx/conf.d/box.samgk.ru.conf
        consistency: cached
    ports:
      - "8080:80"