// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transport/proto/src/url_shortner-service/models.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UrlShortner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         uint64                   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Source     string                   `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	Reduction  string                   `protobuf:"bytes,3,opt,name=Reduction,proto3" json:"Reduction,omitempty"`
	Accesses   *UrlShortner_XAccesses   `protobuf:"bytes,4,opt,name=Accesses,proto3" json:"Accesses,omitempty"`
	Properties *UrlShortner_XProperties `protobuf:"bytes,5,opt,name=Properties,proto3" json:"Properties,omitempty"`
}

func (x *UrlShortner) Reset() {
	*x = UrlShortner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlShortner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlShortner) ProtoMessage() {}

func (x *UrlShortner) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlShortner.ProtoReflect.Descriptor instead.
func (*UrlShortner) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_url_shortner_service_models_proto_rawDescGZIP(), []int{0}
}

func (x *UrlShortner) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UrlShortner) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UrlShortner) GetReduction() string {
	if x != nil {
		return x.Reduction
	}
	return ""
}

func (x *UrlShortner) GetAccesses() *UrlShortner_XAccesses {
	if x != nil {
		return x.Accesses
	}
	return nil
}

func (x *UrlShortner) GetProperties() *UrlShortner_XProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UrlShortner_XAccesses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RolesID       []uint64 `protobuf:"varint,1,rep,packed,name=RolesID,proto3" json:"RolesID,omitempty"`
	PermissionsID []uint64 `protobuf:"varint,2,rep,packed,name=PermissionsID,proto3" json:"PermissionsID,omitempty"`
}

func (x *UrlShortner_XAccesses) Reset() {
	*x = UrlShortner_XAccesses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlShortner_XAccesses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlShortner_XAccesses) ProtoMessage() {}

func (x *UrlShortner_XAccesses) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlShortner_XAccesses.ProtoReflect.Descriptor instead.
func (*UrlShortner_XAccesses) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_url_shortner_service_models_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UrlShortner_XAccesses) GetRolesID() []uint64 {
	if x != nil {
		return x.RolesID
	}
	return nil
}

func (x *UrlShortner_XAccesses) GetPermissionsID() []uint64 {
	if x != nil {
		return x.PermissionsID
	}
	return nil
}

type UrlShortner_XProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                 string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Active               bool                   `protobuf:"varint,2,opt,name=Active,proto3" json:"Active,omitempty"`
	NumberOfUses         int64                  `protobuf:"varint,3,opt,name=NumberOfUses,proto3" json:"NumberOfUses,omitempty"`
	RemainedNumberOfUses int64                  `protobuf:"varint,4,opt,name=RemainedNumberOfUses,proto3" json:"RemainedNumberOfUses,omitempty"`
	StartActive          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=StartActive,proto3" json:"StartActive,omitempty"`
	EndActive            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=EndActive,proto3" json:"EndActive,omitempty"`
}

func (x *UrlShortner_XProperties) Reset() {
	*x = UrlShortner_XProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlShortner_XProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlShortner_XProperties) ProtoMessage() {}

func (x *UrlShortner_XProperties) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlShortner_XProperties.ProtoReflect.Descriptor instead.
func (*UrlShortner_XProperties) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_url_shortner_service_models_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UrlShortner_XProperties) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UrlShortner_XProperties) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UrlShortner_XProperties) GetNumberOfUses() int64 {
	if x != nil {
		return x.NumberOfUses
	}
	return 0
}

func (x *UrlShortner_XProperties) GetRemainedNumberOfUses() int64 {
	if x != nil {
		return x.RemainedNumberOfUses
	}
	return 0
}

func (x *UrlShortner_XProperties) GetStartActive() *timestamppb.Timestamp {
	if x != nil {
		return x.StartActive
	}
	return nil
}

func (x *UrlShortner_XProperties) GetEndActive() *timestamppb.Timestamp {
	if x != nil {
		return x.EndActive
	}
	return nil
}

var File_src_transport_proto_src_url_shortner_service_models_proto protoreflect.FileDescriptor

var file_src_transport_proto_src_url_shortner_service_models_proto_rawDesc = []byte{
	0x0a, 0x39, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x04, 0x0a, 0x0b, 0x55,
	0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3f, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x2e, 0x5f, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x52, 0x08, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x12, 0x45, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x65, 0x72,
	0x2e, 0x5f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0a, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x4b, 0x0a, 0x09, 0x5f, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x49, 0x44, 0x12,
	0x24, 0x0a, 0x0d, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0d, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x49, 0x44, 0x1a, 0x89, 0x02, 0x0a, 0x0b, 0x5f, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x55, 0x73, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x55, 0x73, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x65,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x14, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x45, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_transport_proto_src_url_shortner_service_models_proto_rawDescOnce sync.Once
	file_src_transport_proto_src_url_shortner_service_models_proto_rawDescData = file_src_transport_proto_src_url_shortner_service_models_proto_rawDesc
)

func file_src_transport_proto_src_url_shortner_service_models_proto_rawDescGZIP() []byte {
	file_src_transport_proto_src_url_shortner_service_models_proto_rawDescOnce.Do(func() {
		file_src_transport_proto_src_url_shortner_service_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transport_proto_src_url_shortner_service_models_proto_rawDescData)
	})
	return file_src_transport_proto_src_url_shortner_service_models_proto_rawDescData
}

var file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_transport_proto_src_url_shortner_service_models_proto_goTypes = []interface{}{
	(*UrlShortner)(nil),             // 0: grpc_service.UrlShortner
	(*UrlShortner_XAccesses)(nil),   // 1: grpc_service.UrlShortner._Accesses
	(*UrlShortner_XProperties)(nil), // 2: grpc_service.UrlShortner._Properties
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_src_transport_proto_src_url_shortner_service_models_proto_depIdxs = []int32{
	1, // 0: grpc_service.UrlShortner.Accesses:type_name -> grpc_service.UrlShortner._Accesses
	2, // 1: grpc_service.UrlShortner.Properties:type_name -> grpc_service.UrlShortner._Properties
	3, // 2: grpc_service.UrlShortner._Properties.StartActive:type_name -> google.protobuf.Timestamp
	3, // 3: grpc_service.UrlShortner._Properties.EndActive:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_transport_proto_src_url_shortner_service_models_proto_init() }
func file_src_transport_proto_src_url_shortner_service_models_proto_init() {
	if File_src_transport_proto_src_url_shortner_service_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlShortner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlShortner_XAccesses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlShortner_XProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transport_proto_src_url_shortner_service_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_transport_proto_src_url_shortner_service_models_proto_goTypes,
		DependencyIndexes: file_src_transport_proto_src_url_shortner_service_models_proto_depIdxs,
		MessageInfos:      file_src_transport_proto_src_url_shortner_service_models_proto_msgTypes,
	}.Build()
	File_src_transport_proto_src_url_shortner_service_models_proto = out.File
	file_src_transport_proto_src_url_shortner_service_models_proto_rawDesc = nil
	file_src_transport_proto_src_url_shortner_service_models_proto_goTypes = nil
	file_src_transport_proto_src_url_shortner_service_models_proto_depIdxs = nil
}
