// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: src/transport/proto/src/notifications/popup_notifications-service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PopupNotificationsServiceClient is the client API for PopupNotificationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PopupNotificationsServiceClient interface {
	Create(ctx context.Context, in *PopupNotificationsCreateRequest, opts ...grpc.CallOption) (*PopupNotificationsCreateResponse, error)
	CreateOne(ctx context.Context, in *PopupNotificationsCreateOneRequest, opts ...grpc.CallOption) (*PopupNotificationsCreateOneResponse, error)
}

type popupNotificationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPopupNotificationsServiceClient(cc grpc.ClientConnInterface) PopupNotificationsServiceClient {
	return &popupNotificationsServiceClient{cc}
}

func (c *popupNotificationsServiceClient) Create(ctx context.Context, in *PopupNotificationsCreateRequest, opts ...grpc.CallOption) (*PopupNotificationsCreateResponse, error) {
	out := new(PopupNotificationsCreateResponse)
	err := c.cc.Invoke(ctx, "/grpc_service.PopupNotificationsService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *popupNotificationsServiceClient) CreateOne(ctx context.Context, in *PopupNotificationsCreateOneRequest, opts ...grpc.CallOption) (*PopupNotificationsCreateOneResponse, error) {
	out := new(PopupNotificationsCreateOneResponse)
	err := c.cc.Invoke(ctx, "/grpc_service.PopupNotificationsService/CreateOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PopupNotificationsServiceServer is the server API for PopupNotificationsService service.
// All implementations must embed UnimplementedPopupNotificationsServiceServer
// for forward compatibility
type PopupNotificationsServiceServer interface {
	Create(context.Context, *PopupNotificationsCreateRequest) (*PopupNotificationsCreateResponse, error)
	CreateOne(context.Context, *PopupNotificationsCreateOneRequest) (*PopupNotificationsCreateOneResponse, error)
	mustEmbedUnimplementedPopupNotificationsServiceServer()
}

// UnimplementedPopupNotificationsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPopupNotificationsServiceServer struct {
}

func (UnimplementedPopupNotificationsServiceServer) Create(context.Context, *PopupNotificationsCreateRequest) (*PopupNotificationsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPopupNotificationsServiceServer) CreateOne(context.Context, *PopupNotificationsCreateOneRequest) (*PopupNotificationsCreateOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOne not implemented")
}
func (UnimplementedPopupNotificationsServiceServer) mustEmbedUnimplementedPopupNotificationsServiceServer() {
}

// UnsafePopupNotificationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PopupNotificationsServiceServer will
// result in compilation errors.
type UnsafePopupNotificationsServiceServer interface {
	mustEmbedUnimplementedPopupNotificationsServiceServer()
}

func RegisterPopupNotificationsServiceServer(s grpc.ServiceRegistrar, srv PopupNotificationsServiceServer) {
	s.RegisterService(&PopupNotificationsService_ServiceDesc, srv)
}

func _PopupNotificationsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopupNotificationsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopupNotificationsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_service.PopupNotificationsService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopupNotificationsServiceServer).Create(ctx, req.(*PopupNotificationsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PopupNotificationsService_CreateOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopupNotificationsCreateOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PopupNotificationsServiceServer).CreateOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_service.PopupNotificationsService/CreateOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PopupNotificationsServiceServer).CreateOne(ctx, req.(*PopupNotificationsCreateOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PopupNotificationsService_ServiceDesc is the grpc.ServiceDesc for PopupNotificationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PopupNotificationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_service.PopupNotificationsService",
	HandlerType: (*PopupNotificationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PopupNotificationsService_Create_Handler,
		},
		{
			MethodName: "CreateOne",
			Handler:    _PopupNotificationsService_CreateOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/transport/proto/src/notifications/popup_notifications-service.proto",
}
