// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transport/proto/src/users-service/access_system-service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessSystemCheckUserAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID        uint64   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	RolesID       []uint64 `protobuf:"varint,2,rep,packed,name=RolesID,proto3" json:"RolesID,omitempty"`
	PermissionsID []uint64 `protobuf:"varint,3,rep,packed,name=PermissionsID,proto3" json:"PermissionsID,omitempty"`
}

func (x *AccessSystemCheckUserAccessRequest) Reset() {
	*x = AccessSystemCheckUserAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessSystemCheckUserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSystemCheckUserAccessRequest) ProtoMessage() {}

func (x *AccessSystemCheckUserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSystemCheckUserAccessRequest.ProtoReflect.Descriptor instead.
func (*AccessSystemCheckUserAccessRequest) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_access_system_service_proto_rawDescGZIP(), []int{0}
}

func (x *AccessSystemCheckUserAccessRequest) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AccessSystemCheckUserAccessRequest) GetRolesID() []uint64 {
	if x != nil {
		return x.RolesID
	}
	return nil
}

func (x *AccessSystemCheckUserAccessRequest) GetPermissionsID() []uint64 {
	if x != nil {
		return x.PermissionsID
	}
	return nil
}

type AccessSystemCheckUserAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool `protobuf:"varint,1,opt,name=Allowed,proto3" json:"Allowed,omitempty"`
}

func (x *AccessSystemCheckUserAccessResponse) Reset() {
	*x = AccessSystemCheckUserAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessSystemCheckUserAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSystemCheckUserAccessResponse) ProtoMessage() {}

func (x *AccessSystemCheckUserAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSystemCheckUserAccessResponse.ProtoReflect.Descriptor instead.
func (*AccessSystemCheckUserAccessResponse) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_access_system_service_proto_rawDescGZIP(), []int{1}
}

func (x *AccessSystemCheckUserAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_src_transport_proto_src_users_service_access_system_service_proto protoreflect.FileDescriptor

var file_src_transport_proto_src_users_service_access_system_service_proto_rawDesc = []byte{
	0x0a, 0x41, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x7c, 0x0a, 0x22, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x49, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x07, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x44, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x0d, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x49, 0x44, 0x22,
	0x3f, 0x0a, 0x23, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64,
	0x32, 0x86, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x12, 0x76, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x30, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_transport_proto_src_users_service_access_system_service_proto_rawDescOnce sync.Once
	file_src_transport_proto_src_users_service_access_system_service_proto_rawDescData = file_src_transport_proto_src_users_service_access_system_service_proto_rawDesc
)

func file_src_transport_proto_src_users_service_access_system_service_proto_rawDescGZIP() []byte {
	file_src_transport_proto_src_users_service_access_system_service_proto_rawDescOnce.Do(func() {
		file_src_transport_proto_src_users_service_access_system_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transport_proto_src_users_service_access_system_service_proto_rawDescData)
	})
	return file_src_transport_proto_src_users_service_access_system_service_proto_rawDescData
}

var file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_transport_proto_src_users_service_access_system_service_proto_goTypes = []interface{}{
	(*AccessSystemCheckUserAccessRequest)(nil),  // 0: grpc_service.AccessSystemCheckUserAccessRequest
	(*AccessSystemCheckUserAccessResponse)(nil), // 1: grpc_service.AccessSystemCheckUserAccessResponse
}
var file_src_transport_proto_src_users_service_access_system_service_proto_depIdxs = []int32{
	0, // 0: grpc_service.AccessSystem.CheckUserAccess:input_type -> grpc_service.AccessSystemCheckUserAccessRequest
	1, // 1: grpc_service.AccessSystem.CheckUserAccess:output_type -> grpc_service.AccessSystemCheckUserAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_transport_proto_src_users_service_access_system_service_proto_init() }
func file_src_transport_proto_src_users_service_access_system_service_proto_init() {
	if File_src_transport_proto_src_users_service_access_system_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessSystemCheckUserAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessSystemCheckUserAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transport_proto_src_users_service_access_system_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_transport_proto_src_users_service_access_system_service_proto_goTypes,
		DependencyIndexes: file_src_transport_proto_src_users_service_access_system_service_proto_depIdxs,
		MessageInfos:      file_src_transport_proto_src_users_service_access_system_service_proto_msgTypes,
	}.Build()
	File_src_transport_proto_src_users_service_access_system_service_proto = out.File
	file_src_transport_proto_src_users_service_access_system_service_proto_rawDesc = nil
	file_src_transport_proto_src_users_service_access_system_service_proto_goTypes = nil
	file_src_transport_proto_src_users_service_access_system_service_proto_depIdxs = nil
}
