// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: src/transport/proto/src/users-service/basic_authentication-service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BasicAuthenticationServiceClient is the client API for BasicAuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BasicAuthenticationServiceClient interface {
	Auth(ctx context.Context, in *BasicAuthenticationAuthRequest, opts ...grpc.CallOption) (*BasicAuthenticationAuthResponse, error)
}

type basicAuthenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBasicAuthenticationServiceClient(cc grpc.ClientConnInterface) BasicAuthenticationServiceClient {
	return &basicAuthenticationServiceClient{cc}
}

func (c *basicAuthenticationServiceClient) Auth(ctx context.Context, in *BasicAuthenticationAuthRequest, opts ...grpc.CallOption) (*BasicAuthenticationAuthResponse, error) {
	out := new(BasicAuthenticationAuthResponse)
	err := c.cc.Invoke(ctx, "/grpc_service.BasicAuthenticationService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasicAuthenticationServiceServer is the server API for BasicAuthenticationService service.
// All implementations must embed UnimplementedBasicAuthenticationServiceServer
// for forward compatibility
type BasicAuthenticationServiceServer interface {
	Auth(context.Context, *BasicAuthenticationAuthRequest) (*BasicAuthenticationAuthResponse, error)
	mustEmbedUnimplementedBasicAuthenticationServiceServer()
}

// UnimplementedBasicAuthenticationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBasicAuthenticationServiceServer struct {
}

func (UnimplementedBasicAuthenticationServiceServer) Auth(context.Context, *BasicAuthenticationAuthRequest) (*BasicAuthenticationAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedBasicAuthenticationServiceServer) mustEmbedUnimplementedBasicAuthenticationServiceServer() {
}

// UnsafeBasicAuthenticationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasicAuthenticationServiceServer will
// result in compilation errors.
type UnsafeBasicAuthenticationServiceServer interface {
	mustEmbedUnimplementedBasicAuthenticationServiceServer()
}

func RegisterBasicAuthenticationServiceServer(s grpc.ServiceRegistrar, srv BasicAuthenticationServiceServer) {
	s.RegisterService(&BasicAuthenticationService_ServiceDesc, srv)
}

func _BasicAuthenticationService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicAuthenticationAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicAuthenticationServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_service.BasicAuthenticationService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicAuthenticationServiceServer).Auth(ctx, req.(*BasicAuthenticationAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BasicAuthenticationService_ServiceDesc is the grpc.ServiceDesc for BasicAuthenticationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasicAuthenticationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_service.BasicAuthenticationService",
	HandlerType: (*BasicAuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _BasicAuthenticationService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/transport/proto/src/users-service/basic_authentication-service.proto",
}
