// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: src/transport/proto/src/users-service/basic_authentication-service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BasicAuthenticationClient is the client API for BasicAuthentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BasicAuthenticationClient interface {
	Auth(ctx context.Context, in *BasicAuthenticationAuthRequest, opts ...grpc.CallOption) (*BasicAuthenticationAuthResponse, error)
}

type basicAuthenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewBasicAuthenticationClient(cc grpc.ClientConnInterface) BasicAuthenticationClient {
	return &basicAuthenticationClient{cc}
}

func (c *basicAuthenticationClient) Auth(ctx context.Context, in *BasicAuthenticationAuthRequest, opts ...grpc.CallOption) (*BasicAuthenticationAuthResponse, error) {
	out := new(BasicAuthenticationAuthResponse)
	err := c.cc.Invoke(ctx, "/grpc_service.BasicAuthentication/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasicAuthenticationServer is the server API for BasicAuthentication service.
// All implementations must embed UnimplementedBasicAuthenticationServer
// for forward compatibility
type BasicAuthenticationServer interface {
	Auth(context.Context, *BasicAuthenticationAuthRequest) (*BasicAuthenticationAuthResponse, error)
	mustEmbedUnimplementedBasicAuthenticationServer()
}

// UnimplementedBasicAuthenticationServer must be embedded to have forward compatible implementations.
type UnimplementedBasicAuthenticationServer struct {
}

func (UnimplementedBasicAuthenticationServer) Auth(context.Context, *BasicAuthenticationAuthRequest) (*BasicAuthenticationAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedBasicAuthenticationServer) mustEmbedUnimplementedBasicAuthenticationServer() {}

// UnsafeBasicAuthenticationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasicAuthenticationServer will
// result in compilation errors.
type UnsafeBasicAuthenticationServer interface {
	mustEmbedUnimplementedBasicAuthenticationServer()
}

func RegisterBasicAuthenticationServer(s grpc.ServiceRegistrar, srv BasicAuthenticationServer) {
	s.RegisterService(&BasicAuthentication_ServiceDesc, srv)
}

func _BasicAuthentication_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicAuthenticationAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicAuthenticationServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_service.BasicAuthentication/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicAuthenticationServer).Auth(ctx, req.(*BasicAuthenticationAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BasicAuthentication_ServiceDesc is the grpc.ServiceDesc for BasicAuthentication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasicAuthentication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_service.BasicAuthentication",
	HandlerType: (*BasicAuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _BasicAuthentication_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/transport/proto/src/users-service/basic_authentication-service.proto",
}
