// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transport/proto/src/users-service/users-service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsersGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDs []uint64 `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
}

func (x *UsersGetRequest) Reset() {
	*x = UsersGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersGetRequest) ProtoMessage() {}

func (x *UsersGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersGetRequest.ProtoReflect.Descriptor instead.
func (*UsersGetRequest) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP(), []int{0}
}

func (x *UsersGetRequest) GetIDs() []uint64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type UsersGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*User `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *UsersGetResponse) Reset() {
	*x = UsersGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersGetResponse) ProtoMessage() {}

func (x *UsersGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersGetResponse.ProtoReflect.Descriptor instead.
func (*UsersGetResponse) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP(), []int{1}
}

func (x *UsersGetResponse) GetList() []*User {
	if x != nil {
		return x.List
	}
	return nil
}

type UsersGetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UsersGetOneRequest) Reset() {
	*x = UsersGetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersGetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersGetOneRequest) ProtoMessage() {}

func (x *UsersGetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersGetOneRequest.ProtoReflect.Descriptor instead.
func (*UsersGetOneRequest) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP(), []int{2}
}

func (x *UsersGetOneRequest) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type UsersGetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *UsersGetOneResponse) Reset() {
	*x = UsersGetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersGetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersGetOneResponse) ProtoMessage() {}

func (x *UsersGetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersGetOneResponse.ProtoReflect.Descriptor instead.
func (*UsersGetOneResponse) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP(), []int{3}
}

func (x *UsersGetOneResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_src_transport_proto_src_users_service_users_service_proto protoreflect.FileDescriptor

var file_src_transport_proto_src_users_service_users_service_proto_rawDesc = []byte{
	0x0a, 0x39, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x32, 0x73, 0x72, 0x63, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x72, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a,
	0x0f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x49,
	0x44, 0x73, 0x22, 0x3a, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x24,
	0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x3d, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x32, 0x9c, 0x01, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x44, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x20, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_transport_proto_src_users_service_users_service_proto_rawDescOnce sync.Once
	file_src_transport_proto_src_users_service_users_service_proto_rawDescData = file_src_transport_proto_src_users_service_users_service_proto_rawDesc
)

func file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP() []byte {
	file_src_transport_proto_src_users_service_users_service_proto_rawDescOnce.Do(func() {
		file_src_transport_proto_src_users_service_users_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transport_proto_src_users_service_users_service_proto_rawDescData)
	})
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescData
}

var file_src_transport_proto_src_users_service_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_transport_proto_src_users_service_users_service_proto_goTypes = []interface{}{
	(*UsersGetRequest)(nil),     // 0: grpc_service.UsersGetRequest
	(*UsersGetResponse)(nil),    // 1: grpc_service.UsersGetResponse
	(*UsersGetOneRequest)(nil),  // 2: grpc_service.UsersGetOneRequest
	(*UsersGetOneResponse)(nil), // 3: grpc_service.UsersGetOneResponse
	(*User)(nil),                // 4: grpc_service.User
}
var file_src_transport_proto_src_users_service_users_service_proto_depIdxs = []int32{
	4, // 0: grpc_service.UsersGetResponse.List:type_name -> grpc_service.User
	4, // 1: grpc_service.UsersGetOneResponse.User:type_name -> grpc_service.User
	0, // 2: grpc_service.Users.Get:input_type -> grpc_service.UsersGetRequest
	2, // 3: grpc_service.Users.GetOne:input_type -> grpc_service.UsersGetOneRequest
	1, // 4: grpc_service.Users.Get:output_type -> grpc_service.UsersGetResponse
	3, // 5: grpc_service.Users.GetOne:output_type -> grpc_service.UsersGetOneResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_transport_proto_src_users_service_users_service_proto_init() }
func file_src_transport_proto_src_users_service_users_service_proto_init() {
	if File_src_transport_proto_src_users_service_users_service_proto != nil {
		return
	}
	file_src_transport_proto_src_users_service_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_transport_proto_src_users_service_users_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_users_service_users_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_users_service_users_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersGetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_users_service_users_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersGetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transport_proto_src_users_service_users_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_transport_proto_src_users_service_users_service_proto_goTypes,
		DependencyIndexes: file_src_transport_proto_src_users_service_users_service_proto_depIdxs,
		MessageInfos:      file_src_transport_proto_src_users_service_users_service_proto_msgTypes,
	}.Build()
	File_src_transport_proto_src_users_service_users_service_proto = out.File
	file_src_transport_proto_src_users_service_users_service_proto_rawDesc = nil
	file_src_transport_proto_src_users_service_users_service_proto_goTypes = nil
	file_src_transport_proto_src_users_service_users_service_proto_depIdxs = nil
}
