// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transport/proto/src/users-service/users-service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsersGetInfoBasicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UsersGetInfoBasicRequest) Reset() {
	*x = UsersGetInfoBasicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersGetInfoBasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersGetInfoBasicRequest) ProtoMessage() {}

func (x *UsersGetInfoBasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersGetInfoBasicRequest.ProtoReflect.Descriptor instead.
func (*UsersGetInfoBasicRequest) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP(), []int{0}
}

func (x *UsersGetInfoBasicRequest) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type UsersGetInfoBasicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *UsersGetInfoBasicResponse) Reset() {
	*x = UsersGetInfoBasicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersGetInfoBasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersGetInfoBasicResponse) ProtoMessage() {}

func (x *UsersGetInfoBasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_users_service_users_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersGetInfoBasicResponse.ProtoReflect.Descriptor instead.
func (*UsersGetInfoBasicResponse) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP(), []int{1}
}

func (x *UsersGetInfoBasicResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_src_transport_proto_src_users_service_users_service_proto protoreflect.FileDescriptor

var file_src_transport_proto_src_users_service_users_service_proto_rawDesc = []byte{
	0x0a, 0x39, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x32, 0x73, 0x72, 0x63, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x72, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a,
	0x18, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22, 0x43, 0x0a, 0x19, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x32, 0x63,
	0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x5a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_src_transport_proto_src_users_service_users_service_proto_rawDescOnce sync.Once
	file_src_transport_proto_src_users_service_users_service_proto_rawDescData = file_src_transport_proto_src_users_service_users_service_proto_rawDesc
)

func file_src_transport_proto_src_users_service_users_service_proto_rawDescGZIP() []byte {
	file_src_transport_proto_src_users_service_users_service_proto_rawDescOnce.Do(func() {
		file_src_transport_proto_src_users_service_users_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transport_proto_src_users_service_users_service_proto_rawDescData)
	})
	return file_src_transport_proto_src_users_service_users_service_proto_rawDescData
}

var file_src_transport_proto_src_users_service_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_transport_proto_src_users_service_users_service_proto_goTypes = []interface{}{
	(*UsersGetInfoBasicRequest)(nil),  // 0: grpc_service.UsersGetInfoBasicRequest
	(*UsersGetInfoBasicResponse)(nil), // 1: grpc_service.UsersGetInfoBasicResponse
	(*User)(nil),                      // 2: grpc_service.User
}
var file_src_transport_proto_src_users_service_users_service_proto_depIdxs = []int32{
	2, // 0: grpc_service.UsersGetInfoBasicResponse.User:type_name -> grpc_service.User
	0, // 1: grpc_service.Users.GetInfo:input_type -> grpc_service.UsersGetInfoBasicRequest
	1, // 2: grpc_service.Users.GetInfo:output_type -> grpc_service.UsersGetInfoBasicResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_transport_proto_src_users_service_users_service_proto_init() }
func file_src_transport_proto_src_users_service_users_service_proto_init() {
	if File_src_transport_proto_src_users_service_users_service_proto != nil {
		return
	}
	file_src_transport_proto_src_users_service_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_transport_proto_src_users_service_users_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersGetInfoBasicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_users_service_users_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersGetInfoBasicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transport_proto_src_users_service_users_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_transport_proto_src_users_service_users_service_proto_goTypes,
		DependencyIndexes: file_src_transport_proto_src_users_service_users_service_proto_depIdxs,
		MessageInfos:      file_src_transport_proto_src_users_service_users_service_proto_msgTypes,
	}.Build()
	File_src_transport_proto_src_users_service_users_service_proto = out.File
	file_src_transport_proto_src_users_service_users_service_proto_rawDesc = nil
	file_src_transport_proto_src_users_service_users_service_proto_goTypes = nil
	file_src_transport_proto_src_users_service_users_service_proto_depIdxs = nil
}
