// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transports/proto/src/authentication/requests.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transports_proto_src_authentication_requests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transports_proto_src_authentication_requests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_src_transports_proto_src_authentication_requests_proto_rawDescGZIP(), []int{0}
}

type RegisterHttpRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructors []*HttpRouteConstructor `protobuf:"bytes,1,rep,name=Constructors,proto3" json:"Constructors,omitempty"`
}

func (x *RegisterHttpRouteRequest) Reset() {
	*x = RegisterHttpRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transports_proto_src_authentication_requests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterHttpRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHttpRouteRequest) ProtoMessage() {}

func (x *RegisterHttpRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transports_proto_src_authentication_requests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHttpRouteRequest.ProtoReflect.Descriptor instead.
func (*RegisterHttpRouteRequest) Descriptor() ([]byte, []int) {
	return file_src_transports_proto_src_authentication_requests_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterHttpRouteRequest) GetConstructors() []*HttpRouteConstructor {
	if x != nil {
		return x.Constructors
	}
	return nil
}

var File_src_transports_proto_src_authentication_requests_proto protoreflect.FileDescriptor

var file_src_transports_proto_src_authentication_requests_proto_rawDesc = []byte{
	0x0a, 0x36, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x34, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x72, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e,
	0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x64,
	0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0c, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_src_transports_proto_src_authentication_requests_proto_rawDescOnce sync.Once
	file_src_transports_proto_src_authentication_requests_proto_rawDescData = file_src_transports_proto_src_authentication_requests_proto_rawDesc
)

func file_src_transports_proto_src_authentication_requests_proto_rawDescGZIP() []byte {
	file_src_transports_proto_src_authentication_requests_proto_rawDescOnce.Do(func() {
		file_src_transports_proto_src_authentication_requests_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transports_proto_src_authentication_requests_proto_rawDescData)
	})
	return file_src_transports_proto_src_authentication_requests_proto_rawDescData
}

var file_src_transports_proto_src_authentication_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_transports_proto_src_authentication_requests_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),             // 0: authentication.EmptyRequest
	(*RegisterHttpRouteRequest)(nil), // 1: authentication.RegisterHttpRouteRequest
	(*HttpRouteConstructor)(nil),     // 2: authentication.HttpRouteConstructor
}
var file_src_transports_proto_src_authentication_requests_proto_depIdxs = []int32{
	2, // 0: authentication.RegisterHttpRouteRequest.Constructors:type_name -> authentication.HttpRouteConstructor
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_transports_proto_src_authentication_requests_proto_init() }
func file_src_transports_proto_src_authentication_requests_proto_init() {
	if File_src_transports_proto_src_authentication_requests_proto != nil {
		return
	}
	file_src_transports_proto_src_authentication_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_transports_proto_src_authentication_requests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transports_proto_src_authentication_requests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterHttpRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transports_proto_src_authentication_requests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_transports_proto_src_authentication_requests_proto_goTypes,
		DependencyIndexes: file_src_transports_proto_src_authentication_requests_proto_depIdxs,
		MessageInfos:      file_src_transports_proto_src_authentication_requests_proto_msgTypes,
	}.Build()
	File_src_transports_proto_src_authentication_requests_proto = out.File
	file_src_transports_proto_src_authentication_requests_proto_rawDesc = nil
	file_src_transports_proto_src_authentication_requests_proto_goTypes = nil
	file_src_transports_proto_src_authentication_requests_proto_depIdxs = nil
}
