// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transport/proto/src/app/authentication-service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationBasicAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *AuthenticationBasicAuthRequest) Reset() {
	*x = AuthenticationBasicAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_app_authentication_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationBasicAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationBasicAuthRequest) ProtoMessage() {}

func (x *AuthenticationBasicAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_app_authentication_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationBasicAuthRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationBasicAuthRequest) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_app_authentication_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationBasicAuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticationBasicAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticationBasicAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *AuthenticationBasicAuthResponse) Reset() {
	*x = AuthenticationBasicAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_app_authentication_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticationBasicAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationBasicAuthResponse) ProtoMessage() {}

func (x *AuthenticationBasicAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_app_authentication_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationBasicAuthResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationBasicAuthResponse) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_app_authentication_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationBasicAuthResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_src_transport_proto_src_app_authentication_service_proto protoreflect.FileDescriptor

var file_src_transport_proto_src_app_authentication_service_proto_rawDesc = []byte{
	0x0a, 0x38, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x28, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x58, 0x0a, 0x1e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x49, 0x0a, 0x1f,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61,
	0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x32, 0x7a, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x68, 0x0a, 0x09, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x12, 0x2c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_src_transport_proto_src_app_authentication_service_proto_rawDescOnce sync.Once
	file_src_transport_proto_src_app_authentication_service_proto_rawDescData = file_src_transport_proto_src_app_authentication_service_proto_rawDesc
)

func file_src_transport_proto_src_app_authentication_service_proto_rawDescGZIP() []byte {
	file_src_transport_proto_src_app_authentication_service_proto_rawDescOnce.Do(func() {
		file_src_transport_proto_src_app_authentication_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transport_proto_src_app_authentication_service_proto_rawDescData)
	})
	return file_src_transport_proto_src_app_authentication_service_proto_rawDescData
}

var file_src_transport_proto_src_app_authentication_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_transport_proto_src_app_authentication_service_proto_goTypes = []interface{}{
	(*AuthenticationBasicAuthRequest)(nil),  // 0: grpc_service.AuthenticationBasicAuthRequest
	(*AuthenticationBasicAuthResponse)(nil), // 1: grpc_service.AuthenticationBasicAuthResponse
	(*User)(nil),                            // 2: grpc_service.User
}
var file_src_transport_proto_src_app_authentication_service_proto_depIdxs = []int32{
	2, // 0: grpc_service.AuthenticationBasicAuthResponse.User:type_name -> grpc_service.User
	0, // 1: grpc_service.Authentication.BasicAuth:input_type -> grpc_service.AuthenticationBasicAuthRequest
	1, // 2: grpc_service.Authentication.BasicAuth:output_type -> grpc_service.AuthenticationBasicAuthResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_transport_proto_src_app_authentication_service_proto_init() }
func file_src_transport_proto_src_app_authentication_service_proto_init() {
	if File_src_transport_proto_src_app_authentication_service_proto != nil {
		return
	}
	file_src_transport_proto_src_app_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_transport_proto_src_app_authentication_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationBasicAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_app_authentication_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticationBasicAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transport_proto_src_app_authentication_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_transport_proto_src_app_authentication_service_proto_goTypes,
		DependencyIndexes: file_src_transport_proto_src_app_authentication_service_proto_depIdxs,
		MessageInfos:      file_src_transport_proto_src_app_authentication_service_proto_msgTypes,
	}.Build()
	File_src_transport_proto_src_app_authentication_service_proto = out.File
	file_src_transport_proto_src_app_authentication_service_proto_rawDesc = nil
	file_src_transport_proto_src_app_authentication_service_proto_goTypes = nil
	file_src_transport_proto_src_app_authentication_service_proto_depIdxs = nil
}
