// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transport/proto/src/app/models.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OwnerID     uint64 `protobuf:"varint,2,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Name        uint64 `protobuf:"varint,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description uint64 `protobuf:"varint,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Version     uint64 `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *Project) Reset() {
	*x = Project{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_app_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_app_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_app_models_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Project) GetOwnerID() uint64 {
	if x != nil {
		return x.OwnerID
	}
	return 0
}

func (x *Project) GetName() uint64 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Project) GetDescription() uint64 {
	if x != nil {
		return x.Description
	}
	return 0
}

func (x *Project) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_src_transport_proto_src_app_models_proto protoreflect.FileDescriptor

var file_src_transport_proto_src_app_models_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_transport_proto_src_app_models_proto_rawDescOnce sync.Once
	file_src_transport_proto_src_app_models_proto_rawDescData = file_src_transport_proto_src_app_models_proto_rawDesc
)

func file_src_transport_proto_src_app_models_proto_rawDescGZIP() []byte {
	file_src_transport_proto_src_app_models_proto_rawDescOnce.Do(func() {
		file_src_transport_proto_src_app_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transport_proto_src_app_models_proto_rawDescData)
	})
	return file_src_transport_proto_src_app_models_proto_rawDescData
}

var file_src_transport_proto_src_app_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_transport_proto_src_app_models_proto_goTypes = []interface{}{
	(*Project)(nil), // 0: grpc_service.Project
}
var file_src_transport_proto_src_app_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_transport_proto_src_app_models_proto_init() }
func file_src_transport_proto_src_app_models_proto_init() {
	if File_src_transport_proto_src_app_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_transport_proto_src_app_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Project); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transport_proto_src_app_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_transport_proto_src_app_models_proto_goTypes,
		DependencyIndexes: file_src_transport_proto_src_app_models_proto_depIdxs,
		MessageInfos:      file_src_transport_proto_src_app_models_proto_msgTypes,
	}.Build()
	File_src_transport_proto_src_app_models_proto = out.File
	file_src_transport_proto_src_app_models_proto_rawDesc = nil
	file_src_transport_proto_src_app_models_proto_goTypes = nil
	file_src_transport_proto_src_app_models_proto_depIdxs = nil
}
