// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: src/transport/proto/src/app/projects-service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectsGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDs []uint64 `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
}

func (x *ProjectsGetRequest) Reset() {
	*x = ProjectsGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsGetRequest) ProtoMessage() {}

func (x *ProjectsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectsGetRequest) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_app_projects_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectsGetRequest) GetIDs() []uint64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type ProjectsGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Project `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *ProjectsGetResponse) Reset() {
	*x = ProjectsGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsGetResponse) ProtoMessage() {}

func (x *ProjectsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsGetResponse.ProtoReflect.Descriptor instead.
func (*ProjectsGetResponse) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_app_projects_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectsGetResponse) GetList() []*Project {
	if x != nil {
		return x.List
	}
	return nil
}

type ProjectsGetOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ProjectsGetOneRequest) Reset() {
	*x = ProjectsGetOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectsGetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsGetOneRequest) ProtoMessage() {}

func (x *ProjectsGetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsGetOneRequest.ProtoReflect.Descriptor instead.
func (*ProjectsGetOneRequest) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_app_projects_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectsGetOneRequest) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ProjectsGetOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project *Project `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
}

func (x *ProjectsGetOneResponse) Reset() {
	*x = ProjectsGetOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectsGetOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsGetOneResponse) ProtoMessage() {}

func (x *ProjectsGetOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_transport_proto_src_app_projects_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsGetOneResponse.ProtoReflect.Descriptor instead.
func (*ProjectsGetOneResponse) Descriptor() ([]byte, []int) {
	return file_src_transport_proto_src_app_projects_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectsGetOneResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

var File_src_transport_proto_src_app_projects_service_proto protoreflect.FileDescriptor

var file_src_transport_proto_src_app_projects_service_proto_rawDesc = []byte{
	0x0a, 0x32, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x28, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x12,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x03, 0x49, 0x44, 0x73, 0x22, 0x40, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x22,
	0x49, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x32, 0xb2, 0x01, 0x0a, 0x0f, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x4f, 0x6e, 0x65, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x47, 0x65, 0x74, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_transport_proto_src_app_projects_service_proto_rawDescOnce sync.Once
	file_src_transport_proto_src_app_projects_service_proto_rawDescData = file_src_transport_proto_src_app_projects_service_proto_rawDesc
)

func file_src_transport_proto_src_app_projects_service_proto_rawDescGZIP() []byte {
	file_src_transport_proto_src_app_projects_service_proto_rawDescOnce.Do(func() {
		file_src_transport_proto_src_app_projects_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_transport_proto_src_app_projects_service_proto_rawDescData)
	})
	return file_src_transport_proto_src_app_projects_service_proto_rawDescData
}

var file_src_transport_proto_src_app_projects_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_transport_proto_src_app_projects_service_proto_goTypes = []interface{}{
	(*ProjectsGetRequest)(nil),     // 0: grpc_service.ProjectsGetRequest
	(*ProjectsGetResponse)(nil),    // 1: grpc_service.ProjectsGetResponse
	(*ProjectsGetOneRequest)(nil),  // 2: grpc_service.ProjectsGetOneRequest
	(*ProjectsGetOneResponse)(nil), // 3: grpc_service.ProjectsGetOneResponse
	(*Project)(nil),                // 4: grpc_service.Project
}
var file_src_transport_proto_src_app_projects_service_proto_depIdxs = []int32{
	4, // 0: grpc_service.ProjectsGetResponse.List:type_name -> grpc_service.Project
	4, // 1: grpc_service.ProjectsGetOneResponse.Project:type_name -> grpc_service.Project
	0, // 2: grpc_service.ProjectsService.Get:input_type -> grpc_service.ProjectsGetRequest
	2, // 3: grpc_service.ProjectsService.GetOne:input_type -> grpc_service.ProjectsGetOneRequest
	1, // 4: grpc_service.ProjectsService.Get:output_type -> grpc_service.ProjectsGetResponse
	3, // 5: grpc_service.ProjectsService.GetOne:output_type -> grpc_service.ProjectsGetOneResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_transport_proto_src_app_projects_service_proto_init() }
func file_src_transport_proto_src_app_projects_service_proto_init() {
	if File_src_transport_proto_src_app_projects_service_proto != nil {
		return
	}
	file_src_transport_proto_src_app_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_transport_proto_src_app_projects_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectsGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_app_projects_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectsGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_app_projects_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectsGetOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_transport_proto_src_app_projects_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectsGetOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_transport_proto_src_app_projects_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_transport_proto_src_app_projects_service_proto_goTypes,
		DependencyIndexes: file_src_transport_proto_src_app_projects_service_proto_depIdxs,
		MessageInfos:      file_src_transport_proto_src_app_projects_service_proto_msgTypes,
	}.Build()
	File_src_transport_proto_src_app_projects_service_proto = out.File
	file_src_transport_proto_src_app_projects_service_proto_rawDesc = nil
	file_src_transport_proto_src_app_projects_service_proto_goTypes = nil
	file_src_transport_proto_src_app_projects_service_proto_depIdxs = nil
}
